
CFLAGS=

all: qslog qsrotate

BASE_OBJECTS = qs_util.o

qs_util.o: qs_util.c qs_util.h
	cc $(CFLAGS) -c -I. qs_util.c

qslog: qslog.c $(BASE_OBJECTS)
	cc $(CFLAGS) -I. $(BASE_OBJECTS) -o qslog qslog.c -lpthread
	strip qslog

qsrotate: qsrotate.c $(BASE_OBJECTS)
	cc $(CFLAGS) -I. $(BASE_OBJECTS) -o qsrotate qsrotate.c -lpthread -lz
	strip qsrotate

clean:
	rm -f *.o qslog qsrotate
